title: Cyber B
#logo: /assets/img/headshot_circle.png
#description: SOC Analyst
#show_downloads: true
theme: remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
